### ISSUE TITLE
missing lib.core?

### ISSUE THREAD

**Issue by xelerated** [codingo/Reconnoitre#118]
~/Reconnoitre$ reconnoitre 
Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/Reconnoitre-1.0-py3.6.egg/Reconnoitre/reconnoitre.py", line 7, in <module>
    from lib.core.input import CliArgumentParser
ModuleNotFoundError: No module named 'lib.core'

**Comment by 0xMarcio** [comment]
marc@kali:~/Desktop$ sudo reconnoitre
Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/Reconnoitre-1.0-py3.7.egg/Reconnoitre/reconnoitre.py", line 7, in <module>
    from lib.core.input import CliArgumentParser
ModuleNotFoundError: No module named 'lib'

**Comment by skilfoy** [comment]
I'm having the same issue...

**Comment by AhmedOzil10** [comment]
same here

**Comment by wrathdante** [comment]
Same for me. Did I do something wrong? 10x

root@kali:/home/kali/Desktop/Tests/Reconnoitre# reconnoitre -h
Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/Reconnoitre-1.0-py3.7.egg/Reconnoitre/reconnoitre.py", line 7, in <module>
    from lib.core.input import CliArgumentParser
ModuleNotFoundError: No module named 'lib'

**Comment by attacker34** [comment]
Hi @xelerated Having same issue. Can you please check?

**Comment by revizor1** [comment]
same
