### ISSUE TITLE
lib.core

### ISSUE THREAD

**Issue by harr-sudo** [codingo/Reconnoitre#122]
I have followed the install guide and run python setup.py install

root@kali:/opt/Reconnoitre/Reconnoitre# python reconnoitre.py
Traceback (most recent call last):
  File "reconnoitre.py", line 7, in <module>
    from .lib.core.input import CliArgumentParser
ValueError: Attempted relative import in non-package

root@kali:/opt/Reconnoitre/Reconnoitre# reconnoitre
Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/Reconnoitre-1.0-py2.7.egg/Reconnoitre/reconnoitre.py", line 11, in <module>
    from .lib.service_scan import service_scan
  File "/usr/local/lib/python2.7/dist-packages/Reconnoitre-1.0-py2.7.egg/Reconnoitre/lib/service_scan.py", line 22
    QUICKSCAN = f"nmap {flags} {ip_address} -oA '{output_directory}/{ip_address}.quick'"
                                                                                       ^
SyntaxError: invalid syntax

**Comment by SmoggsTown** [comment]
This is a python 3 project & your stacktrace suggests you've installed via python 2.7.
