### ISSUE TITLE
TypeError: bad operand type for unary +: 'unicode'

### ISSUE THREAD

**Issue by nxdamian** [codingo/Reconnoitre#85]
Hi guys,

Any ideas how to fix this error from Kali 2018.3:

`[+] Writing findings for **.**.**.**
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Lab_scripts/Reconnoitre/Reconnoitre/lib/service_scan.py", line 25, in nmap_scan
    write_recommendations(quickresults, ip_address, output_directory)
  File "/root/Lab_scripts/Reconnoitre/Reconnoitre/lib/file_helper.py", line 125, in write_recommendations
    + j["services"][service]["description"]
TypeError: bad operand type for unary +: 'unicode'
`
Am i missing something in my Kali VM?

**Comment by codingo** [comment]
This is fixed in #84, I'm testing now and about to merge.

**Comment by codingo** [comment]
Closed with #84 

@nxdamian if you update you will no longer see this errror.
