### ISSUE TITLE
Missing library in Kali

### ISSUE THREAD

**Issue by digital-shokunin** [codingo/Reconnoitre#87]
I'm running reconnoitre in Kali, it was working fine before but now, after a git pull I'm getting some other error.

```
Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/Reconnoitre-1.0-py3.6.egg/Reconnoitre/reconnoitre.py", line 6, in <module>
    from lib.core.input import CliArgumentParser
ModuleNotFoundError: No module named 'lib.core'
```

pip says "lib" is already installed.

`pip install lib
Requirement already satisfied: lib in /usr/local/lib/python3.6/dist-packages (3.0.0)
`

Running python3 --version
Python 3.6.8rc1

**Comment by P3J0T** [comment]
Exact same issue, error and environment. Installation works with Python2 however.

**Comment by codingo** [comment]
Sorry, I missed this originally. Have you both run the setup instructions on the repository? This wasn't necessary before, but is now that I've packaged everything.

**Comment by overfl0wd** [comment]
i'm getting the same error using python3 on the 2019.1 virtualbox ova.

any update here?

**Comment by codingo** [comment]
@overfl0wd I'm yet to lab this, admittedly. Looking into it now.

Could you let me know if you ran `setup.py` as well as the command line flags you've used?

**Comment by noraj** [comment]
@codingo Same problem on ArchLinux:

PKGBUILD:

```
# This file is part of BlackArch Linux ( https://www.blackarch.org/ ).
# See COPYING for license details.

pkgname=reconnoitre
pkgver=398.758247a
pkgrel=1
pkgdesc='A security tool for multithreaded information gathering and service enumeration.'
groups=('blackarch' 'blackarch-recon')
arch=('any')
url='https://github.com/codingo/Reconnoitre'
license=('GPL3')
depends=('python' 'python-argparse')
makedepends=('git' 'python-setuptools')
source=("$pkgname::git+https://github.com/codingo/Reconnoitre.git")
sha512sums=('SKIP')

pkgver() {
  cd $pkgname

  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
}

build() {
  cd $pkgname

  python setup.py build
}

package() {
  cd $pkgname

  install -Dm 644 -t "$pkgdir/usr/share/doc/$pkgname/" README.md
  python setup.py install --root="$pkgdir" --optimize=1 --skip-build
}
```

Then on a clean chroot environment:

```
$ blackarch-devtools -t -e reconnoitre -p reconnoitre-398.758247a-1-any.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) reconnoitre-398.758247a-1

Total Installed Size:  0,17 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                                 [########################################################################################] 100%
(1/1) checking package integrity                                                                                                               [########################################################################################] 100%
(1/1) loading package files                                                                                                                    [########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [########################################################################################] 100%
(1/1) checking available disk space                                                                                                            [########################################################################################] 100%
:: Processing package changes...
(1/1) installing reconnoitre                                                                                                                   [########################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Package reconnoitre-398.758247a-1-any.pkg.tar.xz installed correctly! Testing it now...
Traceback (most recent call last):
  File "/usr/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/Reconnoitre/reconnoitre.py", line 6, in <module>
    from lib.core.input import CliArgumentParser
ModuleNotFoundError: No module named 'lib'
An error as ocurred while trying to execute the binary reconnoitre, are you sure that it's the binary name?
```

versions installed:

```
python-appdirs-1.4.3-2  python-packaging-19.0-1  python-pyparsing-2.4.0-1  python-six-1.12.0-1  python-setuptools-1:41.0.1-1 perl-error-0.17027-1  perl-mailtools-2.21-1  perl-timedate-2.30-5  git-2.21.0-1 libnsl-1.2.0-1  python-3.7.3-1  python-argparse-1.4.0-5
```

**Comment by noraj** [comment]
I also tried in a clean python 3.6.8 virtuual environment:

```
$ git clone https://github.com/codingo/Reconnoitre.git
$ cd Reconnoitre
$ python setup.py install
$ reconnoitre
Traceback (most recent call last):
  File "/home/noraj/.pyenv/versions/3.6.8/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/home/noraj/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/noraj/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/noraj/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/noraj/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/noraj/.pyenv/versions/3.6.8/lib/python3.6/site-packages/Reconnoitre-1.0-py3.6.egg/Reconnoitre/reconnoitre.py", line 6, in <module>
    from lib.core.input import CliArgumentParser
ModuleNotFoundError: No module named 'lib'
```

**Comment by noraj** [comment]
@codingo  This seems completely unrelated to the OS or the3.x  python version but to the packaging itself, as it happens on both Kali Linux and ArchLinux, on python 3.6.8-rc1, 3.6.8 and 3.7.3.

**Comment by Edu4rdSHL** [comment]
Hello guys, the package is failing with `ModuleNotFoundError: No module named 'lib.core'` because you're trying to run the script that's outside of the [Reconnoitre folder](https://github.com/codingo/Reconnoitre/tree/master/Reconnoitre) and it's trying to import the [lib folder](https://github.com/codingo/Reconnoitre/tree/master/Reconnoitre/lib), using the setup.py file fix it issue but you already got another one like `ModuleNotFoundError: No module named 'file_helper'` because some [modules - find_dns.py for example](https://github.com/codingo/Reconnoitre/blob/master/Reconnoitre/lib/find_dns.py#L3-L4)  try to use the [file_helper](https://github.com/codingo/Reconnoitre/blob/master/Reconnoitre/lib/file_helper.py) module but they're called outside of that folder (in a previous dir). It's solved importing they like:

```python
from lib.file_helper import check_directory
```
https://github.com/codingo/Reconnoitre/pull/95 will fix it, for now an easy workaround is just use:

```bash
$ git clone https://github.com/codingo/Reconnoitre.git
$ cd Reconnoitre
$ find . -type f -print0 | xargs -0 sed -i 's/from file_helper/from lib.file_helper/g'
$ sudo python setup.py install
```

Then you can run `reconnoitre` from your terminal.

**Comment by dkumardefence** [comment]
Hello codingo, I'm facing the lib.file_helper import issue. Can you please look into this.
![image](https://user-images.githubusercontent.com/44009164/58374526-af11ea00-7f0d-11e9-97fd-84bb06971875.png)

Thanks

**Comment by Edu4rdSHL** [comment]
@dkumardefence what steps are you following?

```
[edu4rdshl@blackarch tmp]$ git clone https://github.com/codingo/Reconnoitre
Cloning into 'Reconnoitre'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 1489 (delta 5), reused 10 (delta 1), pack-reused 1467
Receiving objects: 100% (1489/1489), 357.89 KiB | 389.00 KiB/s, done.
Resolving deltas: 100% (967/967), done.
[edu4rdshl@blackarch tmp]$ cd Reconnoitre
[edu4rdshl@blackarch Reconnoitre]$ ls
assets  LICENSE  MANIFEST.in  README.md  Reconnoitre  setup.py  tests
[edu4rdshl@blackarch Reconnoitre]$ cd Reconnoitre/
[edu4rdshl@blackarch Reconnoitre]$ ls
__init__.py  lib  reconnoitre.py  wordlists
[edu4rdshl@blackarch Reconnoitre]$ python reconnoitre.py 
usage: reconnoitre.py [-h] -t TARGET_HOSTS -o OUTPUT_DIRECTORY [-w WORDLIST]
                      [-p PORT] [--pingsweep] [--dns] [--services]
                      [--hostnames] [--snmp] [--quick] [--virtualhosts]
                      [--ignore-http-codes IGNORE_HTTP_CODES]
                      [--ignore-content-length IGNORE_CONTENT_LENGTH]
                      [--quiet] [--no-udp]
reconnoitre.py: error: the following arguments are required: -t, -o
[edu4rdshl@blackarch Reconnoitre]$ python --version
Python 3.7.3
```

**Comment by dkumardefence** [comment]
@Edu4rdSHL  - I used the python setup.py install and then launching reconnoitre <args> from terminal.
This is my new VM box and in the existing box it just works fine.

Thanks

**Comment by dkumardefence** [comment]
@Edu4rdSHL BTW  python reconnoitre.py works fine too. I was accustomed to use the reconnoitre from terminal(anywhere)
