### ISSUE TITLE
Packages ERROR 

### ISSUE THREAD

**Issue by A-AFTAHI** [codingo/Reconnoitre#96]
Hi thanks for the great tool. i've just discovered the tool but whrn i run it i get the error below. any idea what is the source if the issue?

Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/Reconnoitre-1.0-py2.7.egg/Reconnoitre/reconnoitre.py", line 7, in <module>
    from lib.find_dns import find_dns
  File "/usr/local/lib/python2.7/dist-packages/Reconnoitre-1.0-py2.7.egg/Reconnoitre/lib/find_dns.py", line 3, in <module>
    from lib.file_helper import check_directory
ImportError: No module named lib.file_helper

**Comment by subzer0x0** [comment]
It seems like you are trying to run the script outside of the **Reconnoitre** folder. Go to **Reconnoitre** folder and run this command  `python reconnoitre.py` and it should work now. Similar issue was already discussed [here](https://github.com/codingo/Reconnoitre/issues/87)
